"""Constants for smart_climate integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "smart_climate"
NAME = "Умный климат"
VERSION = "0.1.18"

PLATFORMS = ["select", "number", "switch", "sensor"]

CONF_OUTDOOR_SOURCE_TYPE = "outdoor_source_type"
CONF_OUTDOOR_WEATHER = "outdoor_weather"
CONF_OUTDOOR_SENSOR = "outdoor_sensor"
CONF_AC_MISSING_OUTDOOR_POLICY = "ac_missing_outdoor_policy"
CONF_ROOMS = "rooms"
CONF_ROOM_ID = "room_id"
CONF_ROOM_NAME = "room_name"
CONF_ROOM_ENABLED = "room_enabled"
CONF_ROOM_TEMP_SENSORS = "temp_sensors"
CONF_ROOM_HEAT_CATEGORY_1 = "heat_category_1"
CONF_ROOM_HEAT_CATEGORY_2 = "heat_category_2"
CONF_ROOM_HEAT_CATEGORY_3 = "heat_category_3"
CONF_ROOM_COOL_CATEGORY_1 = "cool_category_1"
CONF_ROOM_COOL_CATEGORY_2 = "cool_category_2"
CONF_ROOM_COOL_CATEGORY_3 = "cool_category_3"
CONF_ROOM_WEATHER_SENSITIVE_CLIMATES = "weather_sensitive_climates"
CONF_ROOM_SHARED_CLIMATES = "shared_climates"
CONF_ROOM_SMART_CLIMATES = "smart_climates"
CONF_ROOM_DUMB_DEVICES = "dumb_devices"
CONF_SHARED_ROOMS = "shared_rooms"
CONF_SHARED_DEVICE_MAP = "shared_device_map"

CONF_MODE = "mode"
CONF_TYPE = "type"
CONF_GLOBAL_TARGET = "global_target"
CONF_GLOBAL_TOLERANCE = "global_tolerance"
CONF_PER_ROOM_TARGETS = "per_room_targets"
CONF_PER_ROOM_TOLERANCES = "per_room_tolerances"

CONF_AGGREGATION = "aggregation"
CONF_HEAT_SMALL = "heat_small"
CONF_HEAT_MEDIUM = "heat_medium"
CONF_HEAT_BIG = "heat_big"
CONF_COOL_SMALL = "cool_small"
CONF_COOL_MEDIUM = "cool_medium"
CONF_COOL_BIG = "cool_big"
CONF_HEAT_CATEGORY2_DIFF = "heat_category2_diff"
CONF_HEAT_CATEGORY3_DIFF = "heat_category3_diff"
CONF_COOL_CATEGORY2_DIFF = "cool_category2_diff"
CONF_COOL_CATEGORY3_DIFF = "cool_category3_diff"

CONF_TOLERANCE = "tolerance"
CONF_DELTA = "delta"
CONF_T_TIME = "t_time"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_MAX_OFFSET = "max_offset"
CONF_STEP_OFFSET = "step_offset"
CONF_MIN_ACTION_INTERVAL = "min_action_interval"

CONF_MIN_OUTDOOR_FOR_HEATPUMP = "min_outdoor_for_heatpump"
CONF_MAX_OUTDOOR_FOR_COOL = "max_outdoor_for_cool"

CONF_AFTER_REACH_SMART = "after_reach_smart"
CONF_AFTER_REACH_DUMB = "after_reach_dumb"
CONF_SHARED_ARBITRATION = "shared_arbitration"
CONF_PRIORITY_ROOM = "priority_room"

MODE_OFF = "off"
MODE_PER_ROOM = "per_room"
MODE_GLOBAL = "global"

TYPE_NORMAL = "normal"
TYPE_FAST = "fast"
TYPE_EXTREME = "extreme"

PHASE_IDLE = "idle"
PHASE_BOOST = "boost"
PHASE_HOLD = "hold"

ARBITRATION_MAX_DEMAND = "max_demand"
ARBITRATION_PRIORITY_ROOM = "priority_room"
ARBITRATION_AVERAGE = "average_request"

AGGREGATION_AVERAGE = "average"
AGGREGATION_MIN = "min"
AGGREGATION_MAX = "max"
AGGREGATION_MEDIAN = "median"
AGGREGATION_FIRST = "first"

OUTDOOR_SOURCE_WEATHER = "weather"
OUTDOOR_SOURCE_SENSOR = "sensor"
OUTDOOR_SOURCE_NONE = "none"

OUTDOOR_POLICY_BLOCK = "block"
OUTDOOR_POLICY_ALLOW = "allow"

DUMB_DEVICE_HEAT = "heat"
DUMB_DEVICE_COOL = "cool"
DUMB_PARTICIPATION_OFF = "off"
DUMB_PARTICIPATION_ALWAYS = "always_on"
DUMB_PARTICIPATION_UNTIL_TARGET = "until_reach_target"
DUMB_DEFAULT_CATEGORY = 2

AFTER_REACH_KEEP_ON = "keep_on"
AFTER_REACH_SET_TARGET = "set_target"
AFTER_REACH_TURN_OFF = "turn_off"

DEFAULT_MODE = MODE_OFF
DEFAULT_TYPE = TYPE_NORMAL
DEFAULT_GLOBAL_TARGET = 22.0
DEFAULT_GLOBAL_TOLERANCE = 0.3
DEFAULT_TOLERANCE = 0.3
DEFAULT_DELTA = 0.5
DEFAULT_T_TIME = 300
DEFAULT_UPDATE_INTERVAL = 45
DEFAULT_MAX_OFFSET = 2.0
DEFAULT_STEP_OFFSET = 0.5
DEFAULT_MIN_ACTION_INTERVAL = 30
DEFAULT_HEAT_SMALL = 0.5
DEFAULT_HEAT_MEDIUM = 1.5
DEFAULT_HEAT_BIG = 3.0
DEFAULT_COOL_SMALL = 0.5
DEFAULT_COOL_MEDIUM = 1.5
DEFAULT_COOL_BIG = 3.0
DEFAULT_HEAT_CATEGORY2_DIFF = DEFAULT_HEAT_MEDIUM
DEFAULT_HEAT_CATEGORY3_DIFF = DEFAULT_HEAT_BIG
DEFAULT_COOL_CATEGORY2_DIFF = DEFAULT_COOL_MEDIUM
DEFAULT_COOL_CATEGORY3_DIFF = DEFAULT_COOL_BIG
DEFAULT_MIN_OUTDOOR_FOR_HEATPUMP = -10.0
DEFAULT_MAX_OUTDOOR_FOR_COOL = 45.0
DEFAULT_AFTER_REACH_SMART = AFTER_REACH_SET_TARGET
DEFAULT_AFTER_REACH_DUMB = AFTER_REACH_TURN_OFF
DEFAULT_SHARED_ARBITRATION = ARBITRATION_MAX_DEMAND
DEFAULT_AC_MISSING_OUTDOOR_POLICY = OUTDOOR_POLICY_BLOCK
DEFAULT_AGGREGATION = AGGREGATION_AVERAGE

COORDINATOR_DEBOUNCE_SECONDS = 3

UPDATE_FAILED_WARNING = "Smart Climate update failed"

OPTIONS_DEFAULTS: dict[str, object] = {
    CONF_MODE: DEFAULT_MODE,
    CONF_TYPE: DEFAULT_TYPE,
    CONF_GLOBAL_TARGET: DEFAULT_GLOBAL_TARGET,
    CONF_GLOBAL_TOLERANCE: DEFAULT_GLOBAL_TOLERANCE,
    CONF_TOLERANCE: DEFAULT_TOLERANCE,
    CONF_DELTA: DEFAULT_DELTA,
    CONF_T_TIME: DEFAULT_T_TIME,
    CONF_UPDATE_INTERVAL: DEFAULT_UPDATE_INTERVAL,
    CONF_MAX_OFFSET: DEFAULT_MAX_OFFSET,
    CONF_STEP_OFFSET: DEFAULT_STEP_OFFSET,
    CONF_MIN_ACTION_INTERVAL: DEFAULT_MIN_ACTION_INTERVAL,
    CONF_HEAT_SMALL: DEFAULT_HEAT_SMALL,
    CONF_HEAT_MEDIUM: DEFAULT_HEAT_MEDIUM,
    CONF_HEAT_BIG: DEFAULT_HEAT_BIG,
    CONF_COOL_SMALL: DEFAULT_COOL_SMALL,
    CONF_COOL_MEDIUM: DEFAULT_COOL_MEDIUM,
    CONF_COOL_BIG: DEFAULT_COOL_BIG,
    CONF_HEAT_CATEGORY2_DIFF: DEFAULT_HEAT_CATEGORY2_DIFF,
    CONF_HEAT_CATEGORY3_DIFF: DEFAULT_HEAT_CATEGORY3_DIFF,
    CONF_COOL_CATEGORY2_DIFF: DEFAULT_COOL_CATEGORY2_DIFF,
    CONF_COOL_CATEGORY3_DIFF: DEFAULT_COOL_CATEGORY3_DIFF,
    CONF_MIN_OUTDOOR_FOR_HEATPUMP: DEFAULT_MIN_OUTDOOR_FOR_HEATPUMP,
    CONF_MAX_OUTDOOR_FOR_COOL: DEFAULT_MAX_OUTDOOR_FOR_COOL,
    CONF_AFTER_REACH_SMART: DEFAULT_AFTER_REACH_SMART,
    CONF_AFTER_REACH_DUMB: DEFAULT_AFTER_REACH_DUMB,
    CONF_SHARED_ARBITRATION: DEFAULT_SHARED_ARBITRATION,
    CONF_AC_MISSING_OUTDOOR_POLICY: DEFAULT_AC_MISSING_OUTDOOR_POLICY,
    CONF_AGGREGATION: DEFAULT_AGGREGATION,
}

DEFAULT_SCAN_INTERVAL = timedelta(seconds=DEFAULT_UPDATE_INTERVAL)
